language: python

matrix:
  include:
    - python: 3.4
      env:
        - COVERAGE=false
    - python: 3.5
      env:
        - COVERAGE=false
    - python: 3.6
      env:
        - COVERAGE=true

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install --yes requests pyyaml mpl-probscale --channel=conda-forge
  - conda install --yes coverage docopt pytest pytest-pep8 --channel=conda-forge
  - conda install --yes wqio --channel=phobson/label/dev
  - pip install coveralls
  - pip install . --no-deps

script:
  - python check_pybmpdb.py --verbose --pep8

after_success:
  - if [ ${COVERAGE} = true ]; then
      coverage run --source pybmpdb check_pybmpdb.py;
      coverage report -m;
      coveralls;
    fi
