language: python

matrix:
  include:
    - python: 3.5
      env:
        - COVERAGE=false
    - python: 3.6
      env:
        - COVERAGE=true

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda create --yes --channel=conda-forge -n test python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib statsmodels seaborn mpl-probscale requests pyyaml coverage docopt pytest pytest-pep8
  - source activate test
  - pip install git+https://github.com/Geosyntec/wqio.git
  - pip install codecov
  - pip install . --no-deps

script:
  - coverage run --source pybmpdb check_pybmpdb.py --verbose --pep8

after_success:
  - if [ ${COVERAGE} = true ]; then
      coverage report -m;
      codecov;
    fi
