package:
  name: pybmpdb
  version: "0.2.x"

source:
  path: ../../

#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 1
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pandas
    - numexpr
    - seaborn
    - pyodbc
    - wqio 0.4.x

  run:
    - python
    - setuptools
    - pandas
    - numexpr
    - pyodbc
    - seaborn
    - statsmodels
    - openpyxl
    - xlrd
    - six
    - wqio 0.4.x

test:
  imports:
    - pybmpdb

  requires:
    - nose
    - wqio

about:
  home: https://github.com/Geosyntec/pybmpdb.git
  license:  BSD License
  summary: 'Connector for the International BMP Database to wqio'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml/configure
